-- ============================================================
-- Meal Planner - seed de 100 recetas de prueba
-- Ejecutar conectado a meal_planner_db.
-- Idempotente para estas recetas: actualiza recetas, ingredientes y pasos.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO ingredients (name, category, calories_per_100g, protein_per_100g, carbs_per_100g, sugars_per_100g, fat_per_100g, fiber_per_100g, is_gluten_free, is_diabetic_friendly, glycemic_index) VALUES
('avena', 'cereal', 389, 16.9, 66.3, 0.9, 6.9, 10.6, FALSE, FALSE, 55),
('yogur', 'lacteo', 61, 3.5, 4.7, 4.7, 3.3, 0, TRUE, TRUE, 35),
('platano', 'fruta', 89, 1.1, 22.8, 12.2, 0.3, 2.6, TRUE, FALSE, 51),
('huevo', 'proteina', 155, 13, 1.1, 1.1, 11, 0, TRUE, TRUE, 0),
('espinacas', 'verdura', 23, 2.9, 3.6, 0.4, 0.4, 2.2, TRUE, TRUE, 15),
('pollo', 'carne', 165, 31, 0, 0, 3.6, 0, TRUE, TRUE, 0),
('arroz', 'cereal', 130, 2.7, 28, 0.1, 0.3, 0.4, TRUE, FALSE, 73),
('brocoli', 'verdura', 34, 2.8, 6.6, 1.7, 0.4, 2.6, TRUE, TRUE, 15),
('lentejas', 'legumbre', 116, 9, 20.1, 1.8, 0.4, 7.9, TRUE, TRUE, 32),
('zanahoria', 'verdura', 41, 0.9, 9.6, 4.7, 0.2, 2.8, TRUE, TRUE, 39),
('patata', 'tuberculo', 77, 2, 17, 0.8, 0.1, 2.2, TRUE, FALSE, 78),
('salmon', 'pescado', 208, 20, 0, 0, 13, 0, TRUE, TRUE, 0),
('ensalada', 'verdura', 17, 1.2, 3.3, 1.2, 0.2, 1.8, TRUE, TRUE, 15),
('garbanzos', 'legumbre', 164, 8.9, 27.4, 4.8, 2.6, 7.6, TRUE, TRUE, 28),
('tomate', 'verdura', 18, 0.9, 3.9, 2.6, 0.2, 1.2, TRUE, TRUE, 15),
('pepino', 'verdura', 15, 0.7, 3.6, 1.7, 0.1, 0.5, TRUE, TRUE, 15),
('ternera', 'carne', 217, 26.1, 0, 0, 11.8, 0, TRUE, TRUE, 0),
('pavo', 'carne', 135, 29, 0, 0, 1.5, 0, TRUE, TRUE, 0),
('atun', 'pescado', 132, 28, 0, 0, 1.3, 0, TRUE, TRUE, 0),
('merluza', 'pescado', 89, 17, 0, 0, 1.9, 0, TRUE, TRUE, 0),
('bacalao', 'pescado', 82, 18, 0, 0, 0.7, 0, TRUE, TRUE, 0),
('tofu', 'proteina vegetal', 76, 8, 1.9, 0.6, 4.8, 0.3, TRUE, TRUE, 15),
('quinoa', 'cereal', 120, 4.4, 21.3, 0.9, 1.9, 2.8, TRUE, TRUE, 53),
('pasta integral', 'cereal', 124, 5.3, 25, 0.7, 0.9, 3.2, FALSE, FALSE, 48),
('pan integral', 'cereal', 247, 13, 41, 6, 4.2, 7, FALSE, FALSE, 50),
('calabacin', 'verdura', 17, 1.2, 3.1, 2.5, 0.3, 1, TRUE, TRUE, 15),
('berenjena', 'verdura', 25, 1, 5.9, 3.5, 0.2, 3, TRUE, TRUE, 15),
('pimiento', 'verdura', 31, 1, 6, 4.2, 0.3, 2.1, TRUE, TRUE, 15),
('cebolla', 'verdura', 40, 1.1, 9.3, 4.2, 0.1, 1.7, TRUE, TRUE, 15),
('ajo', 'verdura', 149, 6.4, 33, 1, 0.5, 2.1, TRUE, TRUE, 30),
('champinones', 'verdura', 22, 3.1, 3.3, 2, 0.3, 1, TRUE, TRUE, 10),
('judias verdes', 'verdura', 31, 1.8, 7, 3.3, 0.1, 3.4, TRUE, TRUE, 15),
('guisantes', 'legumbre', 81, 5.4, 14.5, 5.7, 0.4, 5.1, TRUE, TRUE, 35),
('alubias', 'legumbre', 127, 8.7, 22.8, 0.3, 0.5, 6.4, TRUE, TRUE, 30),
('maiz', 'cereal', 86, 3.2, 19, 6.3, 1.2, 2.7, TRUE, FALSE, 52),
('boniato', 'tuberculo', 86, 1.6, 20.1, 4.2, 0.1, 3, TRUE, FALSE, 61),
('coliflor', 'verdura', 25, 1.9, 5, 1.9, 0.3, 2, TRUE, TRUE, 15),
('repollo', 'verdura', 25, 1.3, 5.8, 3.2, 0.1, 2.5, TRUE, TRUE, 10),
('lechuga', 'verdura', 15, 1.4, 2.9, 0.8, 0.2, 1.3, TRUE, TRUE, 10),
('rucula', 'verdura', 25, 2.6, 3.7, 2.1, 0.7, 1.6, TRUE, TRUE, 10),
('manzana', 'fruta', 52, 0.3, 13.8, 10.4, 0.2, 2.4, TRUE, TRUE, 36),
('pera', 'fruta', 57, 0.4, 15.2, 9.8, 0.1, 3.1, TRUE, TRUE, 38),
('fresas', 'fruta', 32, 0.7, 7.7, 4.9, 0.3, 2, TRUE, TRUE, 40),
('arandanos', 'fruta', 57, 0.7, 14.5, 10, 0.3, 2.4, TRUE, TRUE, 53),
('naranja', 'fruta', 47, 0.9, 11.8, 9.4, 0.1, 2.4, TRUE, TRUE, 43),
('kiwi', 'fruta', 61, 1.1, 14.7, 9, 0.5, 3, TRUE, TRUE, 50),
('aguacate', 'fruta', 160, 2, 8.5, 0.7, 14.7, 6.7, TRUE, TRUE, 15),
('aceite de oliva', 'grasa', 884, 0, 0, 0, 100, 0, TRUE, TRUE, 0),
('almendras', 'fruto seco', 579, 21.2, 21.6, 4.4, 49.9, 12.5, TRUE, TRUE, 15),
('nueces', 'fruto seco', 654, 15.2, 13.7, 2.6, 65.2, 6.7, TRUE, TRUE, 15),
('semillas chia', 'semilla', 486, 16.5, 42.1, 0, 30.7, 34.4, TRUE, TRUE, 30),
('queso fresco', 'lacteo', 98, 11, 3.4, 3.4, 4.3, 0, TRUE, TRUE, 30),
('leche', 'lacteo', 50, 3.3, 4.8, 4.8, 1.9, 0, TRUE, TRUE, 35),
('bebida soja', 'bebida vegetal', 33, 3.3, 0.6, 0.6, 1.8, 0.6, TRUE, TRUE, 30),
('salsa tomate', 'salsa', 29, 1.4, 6, 4, 0.2, 1.5, TRUE, TRUE, 35)
ON CONFLICT (name) DO UPDATE SET category = EXCLUDED.category, calories_per_100g = EXCLUDED.calories_per_100g, protein_per_100g = EXCLUDED.protein_per_100g, carbs_per_100g = EXCLUDED.carbs_per_100g, sugars_per_100g = EXCLUDED.sugars_per_100g, fat_per_100g = EXCLUDED.fat_per_100g, fiber_per_100g = EXCLUDED.fiber_per_100g, is_gluten_free = EXCLUDED.is_gluten_free, is_diabetic_friendly = EXCLUDED.is_diabetic_friendly, glycemic_index = EXCLUDED.glycemic_index;

WITH recipe_seed (name, meal_type, description, servings, tags) AS (
    VALUES
    ('Desayuno Avena con arandanos 1', 'breakfast', 'Desayuno de prueba con avena, yogur, arandanos y almendras.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Huevo con fresas 2', 'breakfast', 'Desayuno de prueba con huevo, espinacas, fresas y nueces.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Pan integral con manzana 3', 'breakfast', 'Desayuno de prueba con pan integral, queso fresco, manzana y semillas chia.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Bebida soja con pera 4', 'breakfast', 'Desayuno de prueba con bebida soja, platano, pera y almendras.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Quinoa con naranja 5', 'breakfast', 'Desayuno de prueba con quinoa, leche, naranja y nueces.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Avena con kiwi 6', 'breakfast', 'Desayuno de prueba con avena, yogur, kiwi y semillas chia.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Huevo con platano 7', 'breakfast', 'Desayuno de prueba con huevo, espinacas, platano y almendras.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Pan integral con arandanos 8', 'breakfast', 'Desayuno de prueba con pan integral, queso fresco, arandanos y nueces.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Bebida soja con fresas 9', 'breakfast', 'Desayuno de prueba con bebida soja, platano, fresas y semillas chia.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Quinoa con manzana 10', 'breakfast', 'Desayuno de prueba con quinoa, leche, manzana y almendras.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Avena con pera 11', 'breakfast', 'Desayuno de prueba con avena, yogur, pera y nueces.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Huevo con naranja 12', 'breakfast', 'Desayuno de prueba con huevo, espinacas, naranja y semillas chia.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Pan integral con kiwi 13', 'breakfast', 'Desayuno de prueba con pan integral, queso fresco, kiwi y almendras.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Bebida soja con platano 14', 'breakfast', 'Desayuno de prueba con bebida soja, platano, platano y nueces.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Quinoa con arandanos 15', 'breakfast', 'Desayuno de prueba con quinoa, leche, arandanos y semillas chia.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Avena con fresas 16', 'breakfast', 'Desayuno de prueba con avena, yogur, fresas y almendras.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Huevo con manzana 17', 'breakfast', 'Desayuno de prueba con huevo, espinacas, manzana y nueces.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Pan integral con pera 18', 'breakfast', 'Desayuno de prueba con pan integral, queso fresco, pera y semillas chia.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Bebida soja con naranja 19', 'breakfast', 'Desayuno de prueba con bebida soja, platano, naranja y almendras.', 1, ARRAY['seed_100', 'breakfast']),
    ('Desayuno Quinoa con kiwi 20', 'breakfast', 'Desayuno de prueba con quinoa, leche, kiwi y nueces.', 1, ARRAY['seed_100', 'breakfast']),
    ('Comida Pollo con arroz 1', 'lunch', 'Comida completa con pollo, arroz, brocoli y calabacin.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Ternera con pasta integral 2', 'lunch', 'Comida completa con ternera, pasta integral, cebolla y berenjena.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Pavo con boniato 3', 'lunch', 'Comida completa con pavo, boniato, berenjena y champinones.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Salmon con garbanzos 4', 'lunch', 'Comida completa con salmon, garbanzos, repollo y zanahoria.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Merluza con guisantes 5', 'lunch', 'Comida completa con merluza, guisantes, brocoli y repollo.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Bacalao con quinoa 6', 'lunch', 'Comida completa con bacalao, quinoa, cebolla y pimiento.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Atun con patata 7', 'lunch', 'Comida completa con atun, patata, berenjena y judias verdes.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Tofu con lentejas 8', 'lunch', 'Comida completa con tofu, lentejas, repollo y brocoli.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Huevo con alubias 9', 'lunch', 'Comida completa con huevo, alubias, brocoli y espinacas.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Pollo con arroz 10', 'lunch', 'Comida completa con pollo, arroz, cebolla y tomate.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Ternera con pasta integral 11', 'lunch', 'Comida completa con ternera, pasta integral, berenjena y cebolla.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Pavo con boniato 12', 'lunch', 'Comida completa con pavo, boniato, repollo y coliflor.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Salmon con garbanzos 13', 'lunch', 'Comida completa con salmon, garbanzos, brocoli y calabacin.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Merluza con guisantes 14', 'lunch', 'Comida completa con merluza, guisantes, cebolla y berenjena.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Bacalao con quinoa 15', 'lunch', 'Comida completa con bacalao, quinoa, berenjena y champinones.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Atun con patata 16', 'lunch', 'Comida completa con atun, patata, repollo y zanahoria.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Tofu con lentejas 17', 'lunch', 'Comida completa con tofu, lentejas, brocoli y repollo.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Huevo con alubias 18', 'lunch', 'Comida completa con huevo, alubias, cebolla y pimiento.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Pollo con arroz 19', 'lunch', 'Comida completa con pollo, arroz, berenjena y judias verdes.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Ternera con pasta integral 20', 'lunch', 'Comida completa con ternera, pasta integral, repollo y brocoli.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Pavo con boniato 21', 'lunch', 'Comida completa con pavo, boniato, brocoli y espinacas.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Salmon con garbanzos 22', 'lunch', 'Comida completa con salmon, garbanzos, cebolla y tomate.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Merluza con guisantes 23', 'lunch', 'Comida completa con merluza, guisantes, berenjena y cebolla.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Bacalao con quinoa 24', 'lunch', 'Comida completa con bacalao, quinoa, repollo y coliflor.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Atun con patata 25', 'lunch', 'Comida completa con atun, patata, brocoli y calabacin.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Tofu con lentejas 26', 'lunch', 'Comida completa con tofu, lentejas, cebolla y berenjena.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Huevo con alubias 27', 'lunch', 'Comida completa con huevo, alubias, berenjena y champinones.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Pollo con arroz 28', 'lunch', 'Comida completa con pollo, arroz, repollo y zanahoria.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Ternera con pasta integral 29', 'lunch', 'Comida completa con ternera, pasta integral, brocoli y repollo.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Pavo con boniato 30', 'lunch', 'Comida completa con pavo, boniato, cebolla y pimiento.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Salmon con garbanzos 31', 'lunch', 'Comida completa con salmon, garbanzos, berenjena y judias verdes.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Merluza con guisantes 32', 'lunch', 'Comida completa con merluza, guisantes, repollo y brocoli.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Bacalao con quinoa 33', 'lunch', 'Comida completa con bacalao, quinoa, brocoli y espinacas.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Atun con patata 34', 'lunch', 'Comida completa con atun, patata, cebolla y tomate.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Tofu con lentejas 35', 'lunch', 'Comida completa con tofu, lentejas, berenjena y cebolla.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Huevo con alubias 36', 'lunch', 'Comida completa con huevo, alubias, repollo y coliflor.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Pollo con arroz 37', 'lunch', 'Comida completa con pollo, arroz, brocoli y calabacin.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Ternera con pasta integral 38', 'lunch', 'Comida completa con ternera, pasta integral, cebolla y berenjena.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Pavo con boniato 39', 'lunch', 'Comida completa con pavo, boniato, berenjena y champinones.', 1, ARRAY['seed_100', 'lunch']),
    ('Comida Salmon con garbanzos 40', 'lunch', 'Comida completa con salmon, garbanzos, repollo y zanahoria.', 1, ARRAY['seed_100', 'lunch']),
    ('Cena Salmon con brocoli 1', 'dinner', 'Cena ligera con salmon, brocoli, pimiento y aguacate.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Merluza con zanahoria 2', 'dinner', 'Cena ligera con merluza, zanahoria, coliflor y quinoa.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Bacalao con coliflor 3', 'dinner', 'Cena ligera con bacalao, coliflor, pimiento y aceite de oliva.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Atun con brocoli 4', 'dinner', 'Cena ligera con atun, brocoli, coliflor y aguacate.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Tofu con zanahoria 5', 'dinner', 'Cena ligera con tofu, zanahoria, pimiento y quinoa.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Huevo con coliflor 6', 'dinner', 'Cena ligera con huevo, coliflor, coliflor y aceite de oliva.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Pollo con brocoli 7', 'dinner', 'Cena ligera con pollo, brocoli, pimiento y aguacate.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Ternera con zanahoria 8', 'dinner', 'Cena ligera con ternera, zanahoria, coliflor y quinoa.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Pavo con coliflor 9', 'dinner', 'Cena ligera con pavo, coliflor, pimiento y aceite de oliva.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Salmon con brocoli 10', 'dinner', 'Cena ligera con salmon, brocoli, coliflor y aguacate.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Merluza con zanahoria 11', 'dinner', 'Cena ligera con merluza, zanahoria, pimiento y quinoa.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Bacalao con coliflor 12', 'dinner', 'Cena ligera con bacalao, coliflor, coliflor y aceite de oliva.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Atun con brocoli 13', 'dinner', 'Cena ligera con atun, brocoli, pimiento y aguacate.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Tofu con zanahoria 14', 'dinner', 'Cena ligera con tofu, zanahoria, coliflor y quinoa.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Huevo con coliflor 15', 'dinner', 'Cena ligera con huevo, coliflor, pimiento y aceite de oliva.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Pollo con brocoli 16', 'dinner', 'Cena ligera con pollo, brocoli, coliflor y aguacate.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Ternera con zanahoria 17', 'dinner', 'Cena ligera con ternera, zanahoria, pimiento y quinoa.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Pavo con coliflor 18', 'dinner', 'Cena ligera con pavo, coliflor, coliflor y aceite de oliva.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Salmon con brocoli 19', 'dinner', 'Cena ligera con salmon, brocoli, pimiento y aguacate.', 1, ARRAY['seed_100', 'dinner']),
    ('Cena Merluza con zanahoria 20', 'dinner', 'Cena ligera con merluza, zanahoria, coliflor y quinoa.', 1, ARRAY['seed_100', 'dinner']),
    ('Snack Queso fresco con almendras 1', 'snack', 'Snack de prueba con queso fresco, manzana y almendras.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Yogur con nueces 2', 'snack', 'Snack de prueba con yogur, pera y nueces.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Atun con pepino 3', 'snack', 'Snack de prueba con atun, naranja y pepino.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Huevo con tomate 4', 'snack', 'Snack de prueba con huevo, kiwi y tomate.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Pera con rucula 5', 'snack', 'Snack de prueba con pera, platano y rucula.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Bebida soja con semillas chia 6', 'snack', 'Snack de prueba con bebida soja, arandanos y semillas chia.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Garbanzos con almendras 7', 'snack', 'Snack de prueba con garbanzos, fresas y almendras.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Tofu con nueces 8', 'snack', 'Snack de prueba con tofu, manzana y nueces.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Pavo con pepino 9', 'snack', 'Snack de prueba con pavo, pera y pepino.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Manzana con tomate 10', 'snack', 'Snack de prueba con manzana, naranja y tomate.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Queso fresco con rucula 11', 'snack', 'Snack de prueba con queso fresco, kiwi y rucula.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Yogur con semillas chia 12', 'snack', 'Snack de prueba con yogur, platano y semillas chia.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Atun con almendras 13', 'snack', 'Snack de prueba con atun, arandanos y almendras.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Huevo con nueces 14', 'snack', 'Snack de prueba con huevo, fresas y nueces.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Pera con pepino 15', 'snack', 'Snack de prueba con pera, manzana y pepino.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Bebida soja con tomate 16', 'snack', 'Snack de prueba con bebida soja, pera y tomate.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Garbanzos con rucula 17', 'snack', 'Snack de prueba con garbanzos, naranja y rucula.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Tofu con semillas chia 18', 'snack', 'Snack de prueba con tofu, kiwi y semillas chia.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Pavo con almendras 19', 'snack', 'Snack de prueba con pavo, platano y almendras.', 1, ARRAY['seed_100', 'snack']),
    ('Snack Manzana con nueces 20', 'snack', 'Snack de prueba con manzana, arandanos y nueces.', 1, ARRAY['seed_100', 'snack'])
)
INSERT INTO recipes (name, meal_type, description, servings, tags, owner_id)
SELECT name, meal_type, description, servings, tags, '00000000-0000-0000-0000-000000000001'::uuid FROM recipe_seed
ON CONFLICT (name) DO UPDATE SET meal_type = EXCLUDED.meal_type, description = EXCLUDED.description, servings = EXCLUDED.servings, tags = EXCLUDED.tags, owner_id = EXCLUDED.owner_id;

WITH recipe_seed (name) AS (VALUES
    ('Desayuno Avena con arandanos 1'),
    ('Desayuno Huevo con fresas 2'),
    ('Desayuno Pan integral con manzana 3'),
    ('Desayuno Bebida soja con pera 4'),
    ('Desayuno Quinoa con naranja 5'),
    ('Desayuno Avena con kiwi 6'),
    ('Desayuno Huevo con platano 7'),
    ('Desayuno Pan integral con arandanos 8'),
    ('Desayuno Bebida soja con fresas 9'),
    ('Desayuno Quinoa con manzana 10'),
    ('Desayuno Avena con pera 11'),
    ('Desayuno Huevo con naranja 12'),
    ('Desayuno Pan integral con kiwi 13'),
    ('Desayuno Bebida soja con platano 14'),
    ('Desayuno Quinoa con arandanos 15'),
    ('Desayuno Avena con fresas 16'),
    ('Desayuno Huevo con manzana 17'),
    ('Desayuno Pan integral con pera 18'),
    ('Desayuno Bebida soja con naranja 19'),
    ('Desayuno Quinoa con kiwi 20'),
    ('Comida Pollo con arroz 1'),
    ('Comida Ternera con pasta integral 2'),
    ('Comida Pavo con boniato 3'),
    ('Comida Salmon con garbanzos 4'),
    ('Comida Merluza con guisantes 5'),
    ('Comida Bacalao con quinoa 6'),
    ('Comida Atun con patata 7'),
    ('Comida Tofu con lentejas 8'),
    ('Comida Huevo con alubias 9'),
    ('Comida Pollo con arroz 10'),
    ('Comida Ternera con pasta integral 11'),
    ('Comida Pavo con boniato 12'),
    ('Comida Salmon con garbanzos 13'),
    ('Comida Merluza con guisantes 14'),
    ('Comida Bacalao con quinoa 15'),
    ('Comida Atun con patata 16'),
    ('Comida Tofu con lentejas 17'),
    ('Comida Huevo con alubias 18'),
    ('Comida Pollo con arroz 19'),
    ('Comida Ternera con pasta integral 20'),
    ('Comida Pavo con boniato 21'),
    ('Comida Salmon con garbanzos 22'),
    ('Comida Merluza con guisantes 23'),
    ('Comida Bacalao con quinoa 24'),
    ('Comida Atun con patata 25'),
    ('Comida Tofu con lentejas 26'),
    ('Comida Huevo con alubias 27'),
    ('Comida Pollo con arroz 28'),
    ('Comida Ternera con pasta integral 29'),
    ('Comida Pavo con boniato 30'),
    ('Comida Salmon con garbanzos 31'),
    ('Comida Merluza con guisantes 32'),
    ('Comida Bacalao con quinoa 33'),
    ('Comida Atun con patata 34'),
    ('Comida Tofu con lentejas 35'),
    ('Comida Huevo con alubias 36'),
    ('Comida Pollo con arroz 37'),
    ('Comida Ternera con pasta integral 38'),
    ('Comida Pavo con boniato 39'),
    ('Comida Salmon con garbanzos 40'),
    ('Cena Salmon con brocoli 1'),
    ('Cena Merluza con zanahoria 2'),
    ('Cena Bacalao con coliflor 3'),
    ('Cena Atun con brocoli 4'),
    ('Cena Tofu con zanahoria 5'),
    ('Cena Huevo con coliflor 6'),
    ('Cena Pollo con brocoli 7'),
    ('Cena Ternera con zanahoria 8'),
    ('Cena Pavo con coliflor 9'),
    ('Cena Salmon con brocoli 10'),
    ('Cena Merluza con zanahoria 11'),
    ('Cena Bacalao con coliflor 12'),
    ('Cena Atun con brocoli 13'),
    ('Cena Tofu con zanahoria 14'),
    ('Cena Huevo con coliflor 15'),
    ('Cena Pollo con brocoli 16'),
    ('Cena Ternera con zanahoria 17'),
    ('Cena Pavo con coliflor 18'),
    ('Cena Salmon con brocoli 19'),
    ('Cena Merluza con zanahoria 20'),
    ('Snack Queso fresco con almendras 1'),
    ('Snack Yogur con nueces 2'),
    ('Snack Atun con pepino 3'),
    ('Snack Huevo con tomate 4'),
    ('Snack Pera con rucula 5'),
    ('Snack Bebida soja con semillas chia 6'),
    ('Snack Garbanzos con almendras 7'),
    ('Snack Tofu con nueces 8'),
    ('Snack Pavo con pepino 9'),
    ('Snack Manzana con tomate 10'),
    ('Snack Queso fresco con rucula 11'),
    ('Snack Yogur con semillas chia 12'),
    ('Snack Atun con almendras 13'),
    ('Snack Huevo con nueces 14'),
    ('Snack Pera con pepino 15'),
    ('Snack Bebida soja con tomate 16'),
    ('Snack Garbanzos con rucula 17'),
    ('Snack Tofu con semillas chia 18'),
    ('Snack Pavo con almendras 19'),
    ('Snack Manzana con nueces 20')
), target_recipes AS (SELECT r.id FROM recipes r JOIN recipe_seed rs ON rs.name = r.name) DELETE FROM recipe_ingredients ri USING target_recipes tr WHERE ri.recipe_id = tr.id;

WITH recipe_seed (name) AS (VALUES
    ('Desayuno Avena con arandanos 1'),
    ('Desayuno Huevo con fresas 2'),
    ('Desayuno Pan integral con manzana 3'),
    ('Desayuno Bebida soja con pera 4'),
    ('Desayuno Quinoa con naranja 5'),
    ('Desayuno Avena con kiwi 6'),
    ('Desayuno Huevo con platano 7'),
    ('Desayuno Pan integral con arandanos 8'),
    ('Desayuno Bebida soja con fresas 9'),
    ('Desayuno Quinoa con manzana 10'),
    ('Desayuno Avena con pera 11'),
    ('Desayuno Huevo con naranja 12'),
    ('Desayuno Pan integral con kiwi 13'),
    ('Desayuno Bebida soja con platano 14'),
    ('Desayuno Quinoa con arandanos 15'),
    ('Desayuno Avena con fresas 16'),
    ('Desayuno Huevo con manzana 17'),
    ('Desayuno Pan integral con pera 18'),
    ('Desayuno Bebida soja con naranja 19'),
    ('Desayuno Quinoa con kiwi 20'),
    ('Comida Pollo con arroz 1'),
    ('Comida Ternera con pasta integral 2'),
    ('Comida Pavo con boniato 3'),
    ('Comida Salmon con garbanzos 4'),
    ('Comida Merluza con guisantes 5'),
    ('Comida Bacalao con quinoa 6'),
    ('Comida Atun con patata 7'),
    ('Comida Tofu con lentejas 8'),
    ('Comida Huevo con alubias 9'),
    ('Comida Pollo con arroz 10'),
    ('Comida Ternera con pasta integral 11'),
    ('Comida Pavo con boniato 12'),
    ('Comida Salmon con garbanzos 13'),
    ('Comida Merluza con guisantes 14'),
    ('Comida Bacalao con quinoa 15'),
    ('Comida Atun con patata 16'),
    ('Comida Tofu con lentejas 17'),
    ('Comida Huevo con alubias 18'),
    ('Comida Pollo con arroz 19'),
    ('Comida Ternera con pasta integral 20'),
    ('Comida Pavo con boniato 21'),
    ('Comida Salmon con garbanzos 22'),
    ('Comida Merluza con guisantes 23'),
    ('Comida Bacalao con quinoa 24'),
    ('Comida Atun con patata 25'),
    ('Comida Tofu con lentejas 26'),
    ('Comida Huevo con alubias 27'),
    ('Comida Pollo con arroz 28'),
    ('Comida Ternera con pasta integral 29'),
    ('Comida Pavo con boniato 30'),
    ('Comida Salmon con garbanzos 31'),
    ('Comida Merluza con guisantes 32'),
    ('Comida Bacalao con quinoa 33'),
    ('Comida Atun con patata 34'),
    ('Comida Tofu con lentejas 35'),
    ('Comida Huevo con alubias 36'),
    ('Comida Pollo con arroz 37'),
    ('Comida Ternera con pasta integral 38'),
    ('Comida Pavo con boniato 39'),
    ('Comida Salmon con garbanzos 40'),
    ('Cena Salmon con brocoli 1'),
    ('Cena Merluza con zanahoria 2'),
    ('Cena Bacalao con coliflor 3'),
    ('Cena Atun con brocoli 4'),
    ('Cena Tofu con zanahoria 5'),
    ('Cena Huevo con coliflor 6'),
    ('Cena Pollo con brocoli 7'),
    ('Cena Ternera con zanahoria 8'),
    ('Cena Pavo con coliflor 9'),
    ('Cena Salmon con brocoli 10'),
    ('Cena Merluza con zanahoria 11'),
    ('Cena Bacalao con coliflor 12'),
    ('Cena Atun con brocoli 13'),
    ('Cena Tofu con zanahoria 14'),
    ('Cena Huevo con coliflor 15'),
    ('Cena Pollo con brocoli 16'),
    ('Cena Ternera con zanahoria 17'),
    ('Cena Pavo con coliflor 18'),
    ('Cena Salmon con brocoli 19'),
    ('Cena Merluza con zanahoria 20'),
    ('Snack Queso fresco con almendras 1'),
    ('Snack Yogur con nueces 2'),
    ('Snack Atun con pepino 3'),
    ('Snack Huevo con tomate 4'),
    ('Snack Pera con rucula 5'),
    ('Snack Bebida soja con semillas chia 6'),
    ('Snack Garbanzos con almendras 7'),
    ('Snack Tofu con nueces 8'),
    ('Snack Pavo con pepino 9'),
    ('Snack Manzana con tomate 10'),
    ('Snack Queso fresco con rucula 11'),
    ('Snack Yogur con semillas chia 12'),
    ('Snack Atun con almendras 13'),
    ('Snack Huevo con nueces 14'),
    ('Snack Pera con pepino 15'),
    ('Snack Bebida soja con tomate 16'),
    ('Snack Garbanzos con rucula 17'),
    ('Snack Tofu con semillas chia 18'),
    ('Snack Pavo con almendras 19'),
    ('Snack Manzana con nueces 20')
), target_recipes AS (SELECT r.id FROM recipes r JOIN recipe_seed rs ON rs.name = r.name) DELETE FROM recipe_steps rs USING target_recipes tr WHERE rs.recipe_id = tr.id;

WITH ingredient_seed (recipe_name, ingredient_name, quantity, unit) AS (
    VALUES
    ('Desayuno Avena con arandanos 1', 'avena', 70, 'g'),
    ('Desayuno Avena con arandanos 1', 'yogur', 160, 'g'),
    ('Desayuno Avena con arandanos 1', 'arandanos', 100, 'g'),
    ('Desayuno Avena con arandanos 1', 'almendras', 15, 'g'),
    ('Desayuno Huevo con fresas 2', 'huevo', 2, 'ud'),
    ('Desayuno Huevo con fresas 2', 'espinacas', 160, 'g'),
    ('Desayuno Huevo con fresas 2', 'fresas', 100, 'g'),
    ('Desayuno Huevo con fresas 2', 'nueces', 15, 'g'),
    ('Desayuno Pan integral con manzana 3', 'pan integral', 70, 'g'),
    ('Desayuno Pan integral con manzana 3', 'queso fresco', 160, 'g'),
    ('Desayuno Pan integral con manzana 3', 'manzana', 100, 'g'),
    ('Desayuno Pan integral con manzana 3', 'semillas chia', 15, 'g'),
    ('Desayuno Bebida soja con pera 4', 'bebida soja', 70, 'g'),
    ('Desayuno Bebida soja con pera 4', 'platano', 1, 'ud'),
    ('Desayuno Bebida soja con pera 4', 'pera', 100, 'g'),
    ('Desayuno Bebida soja con pera 4', 'almendras', 15, 'g'),
    ('Desayuno Quinoa con naranja 5', 'quinoa', 70, 'g'),
    ('Desayuno Quinoa con naranja 5', 'leche', 160, 'g'),
    ('Desayuno Quinoa con naranja 5', 'naranja', 100, 'g'),
    ('Desayuno Quinoa con naranja 5', 'nueces', 15, 'g'),
    ('Desayuno Avena con kiwi 6', 'avena', 70, 'g'),
    ('Desayuno Avena con kiwi 6', 'yogur', 160, 'g'),
    ('Desayuno Avena con kiwi 6', 'kiwi', 100, 'g'),
    ('Desayuno Avena con kiwi 6', 'semillas chia', 15, 'g'),
    ('Desayuno Huevo con platano 7', 'huevo', 2, 'ud'),
    ('Desayuno Huevo con platano 7', 'espinacas', 160, 'g'),
    ('Desayuno Huevo con platano 7', 'platano', 1, 'ud'),
    ('Desayuno Huevo con platano 7', 'almendras', 15, 'g'),
    ('Desayuno Pan integral con arandanos 8', 'pan integral', 70, 'g'),
    ('Desayuno Pan integral con arandanos 8', 'queso fresco', 160, 'g'),
    ('Desayuno Pan integral con arandanos 8', 'arandanos', 100, 'g'),
    ('Desayuno Pan integral con arandanos 8', 'nueces', 15, 'g'),
    ('Desayuno Bebida soja con fresas 9', 'bebida soja', 70, 'g'),
    ('Desayuno Bebida soja con fresas 9', 'platano', 1, 'ud'),
    ('Desayuno Bebida soja con fresas 9', 'fresas', 100, 'g'),
    ('Desayuno Bebida soja con fresas 9', 'semillas chia', 15, 'g'),
    ('Desayuno Quinoa con manzana 10', 'quinoa', 70, 'g'),
    ('Desayuno Quinoa con manzana 10', 'leche', 160, 'g'),
    ('Desayuno Quinoa con manzana 10', 'manzana', 100, 'g'),
    ('Desayuno Quinoa con manzana 10', 'almendras', 15, 'g'),
    ('Desayuno Avena con pera 11', 'avena', 70, 'g'),
    ('Desayuno Avena con pera 11', 'yogur', 160, 'g'),
    ('Desayuno Avena con pera 11', 'pera', 100, 'g'),
    ('Desayuno Avena con pera 11', 'nueces', 15, 'g'),
    ('Desayuno Huevo con naranja 12', 'huevo', 2, 'ud'),
    ('Desayuno Huevo con naranja 12', 'espinacas', 160, 'g'),
    ('Desayuno Huevo con naranja 12', 'naranja', 100, 'g'),
    ('Desayuno Huevo con naranja 12', 'semillas chia', 15, 'g'),
    ('Desayuno Pan integral con kiwi 13', 'pan integral', 70, 'g'),
    ('Desayuno Pan integral con kiwi 13', 'queso fresco', 160, 'g'),
    ('Desayuno Pan integral con kiwi 13', 'kiwi', 100, 'g'),
    ('Desayuno Pan integral con kiwi 13', 'almendras', 15, 'g'),
    ('Desayuno Bebida soja con platano 14', 'bebida soja', 70, 'g'),
    ('Desayuno Bebida soja con platano 14', 'platano', 2, 'ud'),
    ('Desayuno Bebida soja con platano 14', 'nueces', 15, 'g'),
    ('Desayuno Quinoa con arandanos 15', 'quinoa', 70, 'g'),
    ('Desayuno Quinoa con arandanos 15', 'leche', 160, 'g'),
    ('Desayuno Quinoa con arandanos 15', 'arandanos', 100, 'g'),
    ('Desayuno Quinoa con arandanos 15', 'semillas chia', 15, 'g'),
    ('Desayuno Avena con fresas 16', 'avena', 70, 'g'),
    ('Desayuno Avena con fresas 16', 'yogur', 160, 'g'),
    ('Desayuno Avena con fresas 16', 'fresas', 100, 'g'),
    ('Desayuno Avena con fresas 16', 'almendras', 15, 'g'),
    ('Desayuno Huevo con manzana 17', 'huevo', 2, 'ud'),
    ('Desayuno Huevo con manzana 17', 'espinacas', 160, 'g'),
    ('Desayuno Huevo con manzana 17', 'manzana', 100, 'g'),
    ('Desayuno Huevo con manzana 17', 'nueces', 15, 'g'),
    ('Desayuno Pan integral con pera 18', 'pan integral', 70, 'g'),
    ('Desayuno Pan integral con pera 18', 'queso fresco', 160, 'g'),
    ('Desayuno Pan integral con pera 18', 'pera', 100, 'g'),
    ('Desayuno Pan integral con pera 18', 'semillas chia', 15, 'g'),
    ('Desayuno Bebida soja con naranja 19', 'bebida soja', 70, 'g'),
    ('Desayuno Bebida soja con naranja 19', 'platano', 1, 'ud'),
    ('Desayuno Bebida soja con naranja 19', 'naranja', 100, 'g'),
    ('Desayuno Bebida soja con naranja 19', 'almendras', 15, 'g'),
    ('Desayuno Quinoa con kiwi 20', 'quinoa', 70, 'g'),
    ('Desayuno Quinoa con kiwi 20', 'leche', 160, 'g'),
    ('Desayuno Quinoa con kiwi 20', 'kiwi', 100, 'g'),
    ('Desayuno Quinoa con kiwi 20', 'nueces', 15, 'g'),
    ('Comida Pollo con arroz 1', 'pollo', 170, 'g'),
    ('Comida Pollo con arroz 1', 'arroz', 110, 'g'),
    ('Comida Pollo con arroz 1', 'brocoli', 130, 'g'),
    ('Comida Pollo con arroz 1', 'calabacin', 80, 'g'),
    ('Comida Ternera con pasta integral 2', 'ternera', 170, 'g'),
    ('Comida Ternera con pasta integral 2', 'pasta integral', 110, 'g'),
    ('Comida Ternera con pasta integral 2', 'cebolla', 130, 'g'),
    ('Comida Ternera con pasta integral 2', 'berenjena', 80, 'g'),
    ('Comida Pavo con boniato 3', 'pavo', 170, 'g'),
    ('Comida Pavo con boniato 3', 'boniato', 110, 'g'),
    ('Comida Pavo con boniato 3', 'berenjena', 130, 'g'),
    ('Comida Pavo con boniato 3', 'champinones', 80, 'g'),
    ('Comida Salmon con garbanzos 4', 'salmon', 170, 'g'),
    ('Comida Salmon con garbanzos 4', 'garbanzos', 110, 'g'),
    ('Comida Salmon con garbanzos 4', 'repollo', 130, 'g'),
    ('Comida Salmon con garbanzos 4', 'zanahoria', 80, 'g'),
    ('Comida Merluza con guisantes 5', 'merluza', 170, 'g'),
    ('Comida Merluza con guisantes 5', 'guisantes', 110, 'g'),
    ('Comida Merluza con guisantes 5', 'brocoli', 130, 'g'),
    ('Comida Merluza con guisantes 5', 'repollo', 80, 'g'),
    ('Comida Bacalao con quinoa 6', 'bacalao', 170, 'g'),
    ('Comida Bacalao con quinoa 6', 'quinoa', 110, 'g'),
    ('Comida Bacalao con quinoa 6', 'cebolla', 130, 'g'),
    ('Comida Bacalao con quinoa 6', 'pimiento', 80, 'g'),
    ('Comida Atun con patata 7', 'atun', 170, 'g'),
    ('Comida Atun con patata 7', 'patata', 110, 'g'),
    ('Comida Atun con patata 7', 'berenjena', 130, 'g'),
    ('Comida Atun con patata 7', 'judias verdes', 80, 'g'),
    ('Comida Tofu con lentejas 8', 'tofu', 170, 'g'),
    ('Comida Tofu con lentejas 8', 'lentejas', 110, 'g'),
    ('Comida Tofu con lentejas 8', 'repollo', 130, 'g'),
    ('Comida Tofu con lentejas 8', 'brocoli', 80, 'g'),
    ('Comida Huevo con alubias 9', 'huevo', 2, 'ud'),
    ('Comida Huevo con alubias 9', 'alubias', 110, 'g'),
    ('Comida Huevo con alubias 9', 'brocoli', 130, 'g'),
    ('Comida Huevo con alubias 9', 'espinacas', 80, 'g'),
    ('Comida Pollo con arroz 10', 'pollo', 170, 'g'),
    ('Comida Pollo con arroz 10', 'arroz', 110, 'g'),
    ('Comida Pollo con arroz 10', 'cebolla', 130, 'g'),
    ('Comida Pollo con arroz 10', 'tomate', 80, 'g'),
    ('Comida Ternera con pasta integral 11', 'ternera', 170, 'g'),
    ('Comida Ternera con pasta integral 11', 'pasta integral', 110, 'g'),
    ('Comida Ternera con pasta integral 11', 'berenjena', 130, 'g'),
    ('Comida Ternera con pasta integral 11', 'cebolla', 80, 'g'),
    ('Comida Pavo con boniato 12', 'pavo', 170, 'g'),
    ('Comida Pavo con boniato 12', 'boniato', 110, 'g'),
    ('Comida Pavo con boniato 12', 'repollo', 130, 'g'),
    ('Comida Pavo con boniato 12', 'coliflor', 80, 'g'),
    ('Comida Salmon con garbanzos 13', 'salmon', 170, 'g'),
    ('Comida Salmon con garbanzos 13', 'garbanzos', 110, 'g'),
    ('Comida Salmon con garbanzos 13', 'brocoli', 130, 'g'),
    ('Comida Salmon con garbanzos 13', 'calabacin', 80, 'g'),
    ('Comida Merluza con guisantes 14', 'merluza', 170, 'g'),
    ('Comida Merluza con guisantes 14', 'guisantes', 110, 'g'),
    ('Comida Merluza con guisantes 14', 'cebolla', 130, 'g'),
    ('Comida Merluza con guisantes 14', 'berenjena', 80, 'g'),
    ('Comida Bacalao con quinoa 15', 'bacalao', 170, 'g'),
    ('Comida Bacalao con quinoa 15', 'quinoa', 110, 'g'),
    ('Comida Bacalao con quinoa 15', 'berenjena', 130, 'g'),
    ('Comida Bacalao con quinoa 15', 'champinones', 80, 'g'),
    ('Comida Atun con patata 16', 'atun', 170, 'g'),
    ('Comida Atun con patata 16', 'patata', 110, 'g'),
    ('Comida Atun con patata 16', 'repollo', 130, 'g'),
    ('Comida Atun con patata 16', 'zanahoria', 80, 'g'),
    ('Comida Tofu con lentejas 17', 'tofu', 170, 'g'),
    ('Comida Tofu con lentejas 17', 'lentejas', 110, 'g'),
    ('Comida Tofu con lentejas 17', 'brocoli', 130, 'g'),
    ('Comida Tofu con lentejas 17', 'repollo', 80, 'g'),
    ('Comida Huevo con alubias 18', 'huevo', 2, 'ud'),
    ('Comida Huevo con alubias 18', 'alubias', 110, 'g'),
    ('Comida Huevo con alubias 18', 'cebolla', 130, 'g'),
    ('Comida Huevo con alubias 18', 'pimiento', 80, 'g'),
    ('Comida Pollo con arroz 19', 'pollo', 170, 'g'),
    ('Comida Pollo con arroz 19', 'arroz', 110, 'g'),
    ('Comida Pollo con arroz 19', 'berenjena', 130, 'g'),
    ('Comida Pollo con arroz 19', 'judias verdes', 80, 'g'),
    ('Comida Ternera con pasta integral 20', 'ternera', 170, 'g'),
    ('Comida Ternera con pasta integral 20', 'pasta integral', 110, 'g'),
    ('Comida Ternera con pasta integral 20', 'repollo', 130, 'g'),
    ('Comida Ternera con pasta integral 20', 'brocoli', 80, 'g'),
    ('Comida Pavo con boniato 21', 'pavo', 170, 'g'),
    ('Comida Pavo con boniato 21', 'boniato', 110, 'g'),
    ('Comida Pavo con boniato 21', 'brocoli', 130, 'g'),
    ('Comida Pavo con boniato 21', 'espinacas', 80, 'g'),
    ('Comida Salmon con garbanzos 22', 'salmon', 170, 'g'),
    ('Comida Salmon con garbanzos 22', 'garbanzos', 110, 'g'),
    ('Comida Salmon con garbanzos 22', 'cebolla', 130, 'g'),
    ('Comida Salmon con garbanzos 22', 'tomate', 80, 'g'),
    ('Comida Merluza con guisantes 23', 'merluza', 170, 'g'),
    ('Comida Merluza con guisantes 23', 'guisantes', 110, 'g'),
    ('Comida Merluza con guisantes 23', 'berenjena', 130, 'g'),
    ('Comida Merluza con guisantes 23', 'cebolla', 80, 'g'),
    ('Comida Bacalao con quinoa 24', 'bacalao', 170, 'g'),
    ('Comida Bacalao con quinoa 24', 'quinoa', 110, 'g'),
    ('Comida Bacalao con quinoa 24', 'repollo', 130, 'g'),
    ('Comida Bacalao con quinoa 24', 'coliflor', 80, 'g'),
    ('Comida Atun con patata 25', 'atun', 170, 'g'),
    ('Comida Atun con patata 25', 'patata', 110, 'g'),
    ('Comida Atun con patata 25', 'brocoli', 130, 'g'),
    ('Comida Atun con patata 25', 'calabacin', 80, 'g'),
    ('Comida Tofu con lentejas 26', 'tofu', 170, 'g'),
    ('Comida Tofu con lentejas 26', 'lentejas', 110, 'g'),
    ('Comida Tofu con lentejas 26', 'cebolla', 130, 'g'),
    ('Comida Tofu con lentejas 26', 'berenjena', 80, 'g'),
    ('Comida Huevo con alubias 27', 'huevo', 2, 'ud'),
    ('Comida Huevo con alubias 27', 'alubias', 110, 'g'),
    ('Comida Huevo con alubias 27', 'berenjena', 130, 'g'),
    ('Comida Huevo con alubias 27', 'champinones', 80, 'g'),
    ('Comida Pollo con arroz 28', 'pollo', 170, 'g'),
    ('Comida Pollo con arroz 28', 'arroz', 110, 'g'),
    ('Comida Pollo con arroz 28', 'repollo', 130, 'g'),
    ('Comida Pollo con arroz 28', 'zanahoria', 80, 'g'),
    ('Comida Ternera con pasta integral 29', 'ternera', 170, 'g'),
    ('Comida Ternera con pasta integral 29', 'pasta integral', 110, 'g'),
    ('Comida Ternera con pasta integral 29', 'brocoli', 130, 'g'),
    ('Comida Ternera con pasta integral 29', 'repollo', 80, 'g'),
    ('Comida Pavo con boniato 30', 'pavo', 170, 'g'),
    ('Comida Pavo con boniato 30', 'boniato', 110, 'g'),
    ('Comida Pavo con boniato 30', 'cebolla', 130, 'g'),
    ('Comida Pavo con boniato 30', 'pimiento', 80, 'g'),
    ('Comida Salmon con garbanzos 31', 'salmon', 170, 'g'),
    ('Comida Salmon con garbanzos 31', 'garbanzos', 110, 'g'),
    ('Comida Salmon con garbanzos 31', 'berenjena', 130, 'g'),
    ('Comida Salmon con garbanzos 31', 'judias verdes', 80, 'g'),
    ('Comida Merluza con guisantes 32', 'merluza', 170, 'g'),
    ('Comida Merluza con guisantes 32', 'guisantes', 110, 'g'),
    ('Comida Merluza con guisantes 32', 'repollo', 130, 'g'),
    ('Comida Merluza con guisantes 32', 'brocoli', 80, 'g'),
    ('Comida Bacalao con quinoa 33', 'bacalao', 170, 'g'),
    ('Comida Bacalao con quinoa 33', 'quinoa', 110, 'g'),
    ('Comida Bacalao con quinoa 33', 'brocoli', 130, 'g'),
    ('Comida Bacalao con quinoa 33', 'espinacas', 80, 'g'),
    ('Comida Atun con patata 34', 'atun', 170, 'g'),
    ('Comida Atun con patata 34', 'patata', 110, 'g'),
    ('Comida Atun con patata 34', 'cebolla', 130, 'g'),
    ('Comida Atun con patata 34', 'tomate', 80, 'g'),
    ('Comida Tofu con lentejas 35', 'tofu', 170, 'g'),
    ('Comida Tofu con lentejas 35', 'lentejas', 110, 'g'),
    ('Comida Tofu con lentejas 35', 'berenjena', 130, 'g'),
    ('Comida Tofu con lentejas 35', 'cebolla', 80, 'g'),
    ('Comida Huevo con alubias 36', 'huevo', 2, 'ud'),
    ('Comida Huevo con alubias 36', 'alubias', 110, 'g'),
    ('Comida Huevo con alubias 36', 'repollo', 130, 'g'),
    ('Comida Huevo con alubias 36', 'coliflor', 80, 'g'),
    ('Comida Pollo con arroz 37', 'pollo', 170, 'g'),
    ('Comida Pollo con arroz 37', 'arroz', 110, 'g'),
    ('Comida Pollo con arroz 37', 'brocoli', 130, 'g'),
    ('Comida Pollo con arroz 37', 'calabacin', 80, 'g'),
    ('Comida Ternera con pasta integral 38', 'ternera', 170, 'g'),
    ('Comida Ternera con pasta integral 38', 'pasta integral', 110, 'g'),
    ('Comida Ternera con pasta integral 38', 'cebolla', 130, 'g'),
    ('Comida Ternera con pasta integral 38', 'berenjena', 80, 'g'),
    ('Comida Pavo con boniato 39', 'pavo', 170, 'g'),
    ('Comida Pavo con boniato 39', 'boniato', 110, 'g'),
    ('Comida Pavo con boniato 39', 'berenjena', 130, 'g'),
    ('Comida Pavo con boniato 39', 'champinones', 80, 'g'),
    ('Comida Salmon con garbanzos 40', 'salmon', 170, 'g'),
    ('Comida Salmon con garbanzos 40', 'garbanzos', 110, 'g'),
    ('Comida Salmon con garbanzos 40', 'repollo', 130, 'g'),
    ('Comida Salmon con garbanzos 40', 'zanahoria', 80, 'g'),
    ('Cena Salmon con brocoli 1', 'salmon', 160, 'g'),
    ('Cena Salmon con brocoli 1', 'brocoli', 150, 'g'),
    ('Cena Salmon con brocoli 1', 'pimiento', 90, 'g'),
    ('Cena Salmon con brocoli 1', 'aguacate', 70, 'g'),
    ('Cena Merluza con zanahoria 2', 'merluza', 160, 'g'),
    ('Cena Merluza con zanahoria 2', 'zanahoria', 150, 'g'),
    ('Cena Merluza con zanahoria 2', 'coliflor', 90, 'g'),
    ('Cena Merluza con zanahoria 2', 'quinoa', 70, 'g'),
    ('Cena Bacalao con coliflor 3', 'bacalao', 160, 'g'),
    ('Cena Bacalao con coliflor 3', 'coliflor', 150, 'g'),
    ('Cena Bacalao con coliflor 3', 'pimiento', 90, 'g'),
    ('Cena Bacalao con coliflor 3', 'aceite de oliva', 8, 'g'),
    ('Cena Atun con brocoli 4', 'atun', 160, 'g'),
    ('Cena Atun con brocoli 4', 'brocoli', 150, 'g'),
    ('Cena Atun con brocoli 4', 'coliflor', 90, 'g'),
    ('Cena Atun con brocoli 4', 'aguacate', 70, 'g'),
    ('Cena Tofu con zanahoria 5', 'tofu', 160, 'g'),
    ('Cena Tofu con zanahoria 5', 'zanahoria', 150, 'g'),
    ('Cena Tofu con zanahoria 5', 'pimiento', 90, 'g'),
    ('Cena Tofu con zanahoria 5', 'quinoa', 70, 'g'),
    ('Cena Huevo con coliflor 6', 'huevo', 2, 'ud'),
    ('Cena Huevo con coliflor 6', 'coliflor', 240, 'g'),
    ('Cena Huevo con coliflor 6', 'aceite de oliva', 8, 'g'),
    ('Cena Pollo con brocoli 7', 'pollo', 160, 'g'),
    ('Cena Pollo con brocoli 7', 'brocoli', 150, 'g'),
    ('Cena Pollo con brocoli 7', 'pimiento', 90, 'g'),
    ('Cena Pollo con brocoli 7', 'aguacate', 70, 'g'),
    ('Cena Ternera con zanahoria 8', 'ternera', 160, 'g'),
    ('Cena Ternera con zanahoria 8', 'zanahoria', 150, 'g'),
    ('Cena Ternera con zanahoria 8', 'coliflor', 90, 'g'),
    ('Cena Ternera con zanahoria 8', 'quinoa', 70, 'g'),
    ('Cena Pavo con coliflor 9', 'pavo', 160, 'g'),
    ('Cena Pavo con coliflor 9', 'coliflor', 150, 'g'),
    ('Cena Pavo con coliflor 9', 'pimiento', 90, 'g'),
    ('Cena Pavo con coliflor 9', 'aceite de oliva', 8, 'g'),
    ('Cena Salmon con brocoli 10', 'salmon', 160, 'g'),
    ('Cena Salmon con brocoli 10', 'brocoli', 150, 'g'),
    ('Cena Salmon con brocoli 10', 'coliflor', 90, 'g'),
    ('Cena Salmon con brocoli 10', 'aguacate', 70, 'g'),
    ('Cena Merluza con zanahoria 11', 'merluza', 160, 'g'),
    ('Cena Merluza con zanahoria 11', 'zanahoria', 150, 'g'),
    ('Cena Merluza con zanahoria 11', 'pimiento', 90, 'g'),
    ('Cena Merluza con zanahoria 11', 'quinoa', 70, 'g'),
    ('Cena Bacalao con coliflor 12', 'bacalao', 160, 'g'),
    ('Cena Bacalao con coliflor 12', 'coliflor', 240, 'g'),
    ('Cena Bacalao con coliflor 12', 'aceite de oliva', 8, 'g'),
    ('Cena Atun con brocoli 13', 'atun', 160, 'g'),
    ('Cena Atun con brocoli 13', 'brocoli', 150, 'g'),
    ('Cena Atun con brocoli 13', 'pimiento', 90, 'g'),
    ('Cena Atun con brocoli 13', 'aguacate', 70, 'g'),
    ('Cena Tofu con zanahoria 14', 'tofu', 160, 'g'),
    ('Cena Tofu con zanahoria 14', 'zanahoria', 150, 'g'),
    ('Cena Tofu con zanahoria 14', 'coliflor', 90, 'g'),
    ('Cena Tofu con zanahoria 14', 'quinoa', 70, 'g'),
    ('Cena Huevo con coliflor 15', 'huevo', 2, 'ud'),
    ('Cena Huevo con coliflor 15', 'coliflor', 150, 'g'),
    ('Cena Huevo con coliflor 15', 'pimiento', 90, 'g'),
    ('Cena Huevo con coliflor 15', 'aceite de oliva', 8, 'g'),
    ('Cena Pollo con brocoli 16', 'pollo', 160, 'g'),
    ('Cena Pollo con brocoli 16', 'brocoli', 150, 'g'),
    ('Cena Pollo con brocoli 16', 'coliflor', 90, 'g'),
    ('Cena Pollo con brocoli 16', 'aguacate', 70, 'g'),
    ('Cena Ternera con zanahoria 17', 'ternera', 160, 'g'),
    ('Cena Ternera con zanahoria 17', 'zanahoria', 150, 'g'),
    ('Cena Ternera con zanahoria 17', 'pimiento', 90, 'g'),
    ('Cena Ternera con zanahoria 17', 'quinoa', 70, 'g'),
    ('Cena Pavo con coliflor 18', 'pavo', 160, 'g'),
    ('Cena Pavo con coliflor 18', 'coliflor', 240, 'g'),
    ('Cena Pavo con coliflor 18', 'aceite de oliva', 8, 'g'),
    ('Cena Salmon con brocoli 19', 'salmon', 160, 'g'),
    ('Cena Salmon con brocoli 19', 'brocoli', 150, 'g'),
    ('Cena Salmon con brocoli 19', 'pimiento', 90, 'g'),
    ('Cena Salmon con brocoli 19', 'aguacate', 70, 'g'),
    ('Cena Merluza con zanahoria 20', 'merluza', 160, 'g'),
    ('Cena Merluza con zanahoria 20', 'zanahoria', 150, 'g'),
    ('Cena Merluza con zanahoria 20', 'coliflor', 90, 'g'),
    ('Cena Merluza con zanahoria 20', 'quinoa', 70, 'g'),
    ('Snack Queso fresco con almendras 1', 'queso fresco', 120, 'g'),
    ('Snack Queso fresco con almendras 1', 'manzana', 90, 'g'),
    ('Snack Queso fresco con almendras 1', 'almendras', 15, 'g'),
    ('Snack Yogur con nueces 2', 'yogur', 120, 'g'),
    ('Snack Yogur con nueces 2', 'pera', 90, 'g'),
    ('Snack Yogur con nueces 2', 'nueces', 15, 'g'),
    ('Snack Atun con pepino 3', 'atun', 120, 'g'),
    ('Snack Atun con pepino 3', 'naranja', 90, 'g'),
    ('Snack Atun con pepino 3', 'pepino', 70, 'g'),
    ('Snack Huevo con tomate 4', 'huevo', 1, 'ud'),
    ('Snack Huevo con tomate 4', 'kiwi', 90, 'g'),
    ('Snack Huevo con tomate 4', 'tomate', 70, 'g'),
    ('Snack Pera con rucula 5', 'pera', 120, 'g'),
    ('Snack Pera con rucula 5', 'platano', 1, 'ud'),
    ('Snack Pera con rucula 5', 'rucula', 70, 'g'),
    ('Snack Bebida soja con semillas chia 6', 'bebida soja', 120, 'g'),
    ('Snack Bebida soja con semillas chia 6', 'arandanos', 90, 'g'),
    ('Snack Bebida soja con semillas chia 6', 'semillas chia', 15, 'g'),
    ('Snack Garbanzos con almendras 7', 'garbanzos', 120, 'g'),
    ('Snack Garbanzos con almendras 7', 'fresas', 90, 'g'),
    ('Snack Garbanzos con almendras 7', 'almendras', 15, 'g'),
    ('Snack Tofu con nueces 8', 'tofu', 120, 'g'),
    ('Snack Tofu con nueces 8', 'manzana', 90, 'g'),
    ('Snack Tofu con nueces 8', 'nueces', 15, 'g'),
    ('Snack Pavo con pepino 9', 'pavo', 120, 'g'),
    ('Snack Pavo con pepino 9', 'pera', 90, 'g'),
    ('Snack Pavo con pepino 9', 'pepino', 70, 'g'),
    ('Snack Manzana con tomate 10', 'manzana', 120, 'g'),
    ('Snack Manzana con tomate 10', 'naranja', 90, 'g'),
    ('Snack Manzana con tomate 10', 'tomate', 70, 'g'),
    ('Snack Queso fresco con rucula 11', 'queso fresco', 120, 'g'),
    ('Snack Queso fresco con rucula 11', 'kiwi', 90, 'g'),
    ('Snack Queso fresco con rucula 11', 'rucula', 70, 'g'),
    ('Snack Yogur con semillas chia 12', 'yogur', 120, 'g'),
    ('Snack Yogur con semillas chia 12', 'platano', 1, 'ud'),
    ('Snack Yogur con semillas chia 12', 'semillas chia', 15, 'g'),
    ('Snack Atun con almendras 13', 'atun', 120, 'g'),
    ('Snack Atun con almendras 13', 'arandanos', 90, 'g'),
    ('Snack Atun con almendras 13', 'almendras', 15, 'g'),
    ('Snack Huevo con nueces 14', 'huevo', 1, 'ud'),
    ('Snack Huevo con nueces 14', 'fresas', 90, 'g'),
    ('Snack Huevo con nueces 14', 'nueces', 15, 'g'),
    ('Snack Pera con pepino 15', 'pera', 120, 'g'),
    ('Snack Pera con pepino 15', 'manzana', 90, 'g'),
    ('Snack Pera con pepino 15', 'pepino', 70, 'g'),
    ('Snack Bebida soja con tomate 16', 'bebida soja', 120, 'g'),
    ('Snack Bebida soja con tomate 16', 'pera', 90, 'g'),
    ('Snack Bebida soja con tomate 16', 'tomate', 70, 'g'),
    ('Snack Garbanzos con rucula 17', 'garbanzos', 120, 'g'),
    ('Snack Garbanzos con rucula 17', 'naranja', 90, 'g'),
    ('Snack Garbanzos con rucula 17', 'rucula', 70, 'g'),
    ('Snack Tofu con semillas chia 18', 'tofu', 120, 'g'),
    ('Snack Tofu con semillas chia 18', 'kiwi', 90, 'g'),
    ('Snack Tofu con semillas chia 18', 'semillas chia', 15, 'g'),
    ('Snack Pavo con almendras 19', 'pavo', 120, 'g'),
    ('Snack Pavo con almendras 19', 'platano', 1, 'ud'),
    ('Snack Pavo con almendras 19', 'almendras', 15, 'g'),
    ('Snack Manzana con nueces 20', 'manzana', 120, 'g'),
    ('Snack Manzana con nueces 20', 'arandanos', 90, 'g'),
    ('Snack Manzana con nueces 20', 'nueces', 15, 'g')
)
INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity, unit)
SELECT r.id, i.id, seed.quantity, seed.unit FROM ingredient_seed seed JOIN recipes r ON r.name = seed.recipe_name JOIN ingredients i ON i.name = seed.ingredient_name;

WITH step_seed (recipe_name, step_number, description) AS (
    VALUES
    ('Desayuno Avena con arandanos 1', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Avena con arandanos 1', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Avena con arandanos 1', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Avena con arandanos 1', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Huevo con fresas 2', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Huevo con fresas 2', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Huevo con fresas 2', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Huevo con fresas 2', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Pan integral con manzana 3', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Pan integral con manzana 3', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Pan integral con manzana 3', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Pan integral con manzana 3', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Bebida soja con pera 4', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Bebida soja con pera 4', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Bebida soja con pera 4', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Bebida soja con pera 4', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Quinoa con naranja 5', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Quinoa con naranja 5', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Quinoa con naranja 5', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Quinoa con naranja 5', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Avena con kiwi 6', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Avena con kiwi 6', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Avena con kiwi 6', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Avena con kiwi 6', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Huevo con platano 7', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Huevo con platano 7', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Huevo con platano 7', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Huevo con platano 7', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Pan integral con arandanos 8', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Pan integral con arandanos 8', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Pan integral con arandanos 8', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Pan integral con arandanos 8', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Bebida soja con fresas 9', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Bebida soja con fresas 9', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Bebida soja con fresas 9', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Bebida soja con fresas 9', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Quinoa con manzana 10', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Quinoa con manzana 10', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Quinoa con manzana 10', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Quinoa con manzana 10', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Avena con pera 11', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Avena con pera 11', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Avena con pera 11', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Avena con pera 11', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Huevo con naranja 12', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Huevo con naranja 12', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Huevo con naranja 12', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Huevo con naranja 12', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Pan integral con kiwi 13', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Pan integral con kiwi 13', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Pan integral con kiwi 13', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Pan integral con kiwi 13', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Bebida soja con platano 14', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Bebida soja con platano 14', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Bebida soja con platano 14', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Bebida soja con platano 14', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Quinoa con arandanos 15', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Quinoa con arandanos 15', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Quinoa con arandanos 15', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Quinoa con arandanos 15', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Avena con fresas 16', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Avena con fresas 16', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Avena con fresas 16', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Avena con fresas 16', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Huevo con manzana 17', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Huevo con manzana 17', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Huevo con manzana 17', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Huevo con manzana 17', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Pan integral con pera 18', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Pan integral con pera 18', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Pan integral con pera 18', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Pan integral con pera 18', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Bebida soja con naranja 19', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Bebida soja con naranja 19', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Bebida soja con naranja 19', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Bebida soja con naranja 19', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Desayuno Quinoa con kiwi 20', 1, 'Preparar los ingredientes y medir las cantidades del desayuno.'),
    ('Desayuno Quinoa con kiwi 20', 2, 'Cocinar o montar la base hasta conseguir la textura deseada.'),
    ('Desayuno Quinoa con kiwi 20', 3, 'Anadir fruta, semillas o acompanamientos y mezclar con cuidado.'),
    ('Desayuno Quinoa con kiwi 20', 4, 'Servir inmediatamente o conservar frio si es una preparacion tipo bol.'),
    ('Comida Pollo con arroz 1', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Pollo con arroz 1', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Pollo con arroz 1', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Pollo con arroz 1', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Ternera con pasta integral 2', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Ternera con pasta integral 2', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Ternera con pasta integral 2', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Ternera con pasta integral 2', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Pavo con boniato 3', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Pavo con boniato 3', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Pavo con boniato 3', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Pavo con boniato 3', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Salmon con garbanzos 4', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Salmon con garbanzos 4', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Salmon con garbanzos 4', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Salmon con garbanzos 4', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Merluza con guisantes 5', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Merluza con guisantes 5', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Merluza con guisantes 5', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Merluza con guisantes 5', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Bacalao con quinoa 6', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Bacalao con quinoa 6', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Bacalao con quinoa 6', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Bacalao con quinoa 6', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Atun con patata 7', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Atun con patata 7', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Atun con patata 7', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Atun con patata 7', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Tofu con lentejas 8', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Tofu con lentejas 8', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Tofu con lentejas 8', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Tofu con lentejas 8', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Huevo con alubias 9', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Huevo con alubias 9', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Huevo con alubias 9', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Huevo con alubias 9', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Pollo con arroz 10', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Pollo con arroz 10', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Pollo con arroz 10', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Pollo con arroz 10', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Ternera con pasta integral 11', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Ternera con pasta integral 11', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Ternera con pasta integral 11', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Ternera con pasta integral 11', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Pavo con boniato 12', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Pavo con boniato 12', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Pavo con boniato 12', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Pavo con boniato 12', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Salmon con garbanzos 13', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Salmon con garbanzos 13', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Salmon con garbanzos 13', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Salmon con garbanzos 13', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Merluza con guisantes 14', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Merluza con guisantes 14', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Merluza con guisantes 14', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Merluza con guisantes 14', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Bacalao con quinoa 15', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Bacalao con quinoa 15', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Bacalao con quinoa 15', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Bacalao con quinoa 15', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Atun con patata 16', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Atun con patata 16', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Atun con patata 16', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Atun con patata 16', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Tofu con lentejas 17', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Tofu con lentejas 17', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Tofu con lentejas 17', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Tofu con lentejas 17', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Huevo con alubias 18', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Huevo con alubias 18', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Huevo con alubias 18', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Huevo con alubias 18', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Pollo con arroz 19', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Pollo con arroz 19', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Pollo con arroz 19', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Pollo con arroz 19', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Ternera con pasta integral 20', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Ternera con pasta integral 20', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Ternera con pasta integral 20', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Ternera con pasta integral 20', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Pavo con boniato 21', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Pavo con boniato 21', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Pavo con boniato 21', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Pavo con boniato 21', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Salmon con garbanzos 22', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Salmon con garbanzos 22', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Salmon con garbanzos 22', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Salmon con garbanzos 22', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Merluza con guisantes 23', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Merluza con guisantes 23', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Merluza con guisantes 23', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Merluza con guisantes 23', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Bacalao con quinoa 24', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Bacalao con quinoa 24', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Bacalao con quinoa 24', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Bacalao con quinoa 24', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Atun con patata 25', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Atun con patata 25', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Atun con patata 25', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Atun con patata 25', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Tofu con lentejas 26', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Tofu con lentejas 26', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Tofu con lentejas 26', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Tofu con lentejas 26', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Huevo con alubias 27', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Huevo con alubias 27', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Huevo con alubias 27', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Huevo con alubias 27', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Pollo con arroz 28', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Pollo con arroz 28', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Pollo con arroz 28', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Pollo con arroz 28', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Ternera con pasta integral 29', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Ternera con pasta integral 29', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Ternera con pasta integral 29', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Ternera con pasta integral 29', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Pavo con boniato 30', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Pavo con boniato 30', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Pavo con boniato 30', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Pavo con boniato 30', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Salmon con garbanzos 31', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Salmon con garbanzos 31', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Salmon con garbanzos 31', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Salmon con garbanzos 31', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Merluza con guisantes 32', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Merluza con guisantes 32', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Merluza con guisantes 32', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Merluza con guisantes 32', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Bacalao con quinoa 33', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Bacalao con quinoa 33', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Bacalao con quinoa 33', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Bacalao con quinoa 33', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Atun con patata 34', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Atun con patata 34', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Atun con patata 34', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Atun con patata 34', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Tofu con lentejas 35', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Tofu con lentejas 35', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Tofu con lentejas 35', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Tofu con lentejas 35', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Huevo con alubias 36', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Huevo con alubias 36', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Huevo con alubias 36', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Huevo con alubias 36', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Pollo con arroz 37', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Pollo con arroz 37', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Pollo con arroz 37', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Pollo con arroz 37', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Ternera con pasta integral 38', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Ternera con pasta integral 38', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Ternera con pasta integral 38', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Ternera con pasta integral 38', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Pavo con boniato 39', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Pavo con boniato 39', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Pavo con boniato 39', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Pavo con boniato 39', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Comida Salmon con garbanzos 40', 1, 'Preparar proteina, guarnicion y verduras antes de cocinar.'),
    ('Comida Salmon con garbanzos 40', 2, 'Cocinar la proteina y la guarnicion hasta que esten en su punto.'),
    ('Comida Salmon con garbanzos 40', 3, 'Saltear o cocer las verduras y combinar todos los componentes.'),
    ('Comida Salmon con garbanzos 40', 4, 'Servir en la racion indicada y guardar sobrantes si los hubiera.'),
    ('Cena Salmon con brocoli 1', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Salmon con brocoli 1', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Salmon con brocoli 1', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Salmon con brocoli 1', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Merluza con zanahoria 2', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Merluza con zanahoria 2', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Merluza con zanahoria 2', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Merluza con zanahoria 2', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Bacalao con coliflor 3', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Bacalao con coliflor 3', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Bacalao con coliflor 3', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Bacalao con coliflor 3', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Atun con brocoli 4', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Atun con brocoli 4', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Atun con brocoli 4', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Atun con brocoli 4', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Tofu con zanahoria 5', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Tofu con zanahoria 5', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Tofu con zanahoria 5', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Tofu con zanahoria 5', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Huevo con coliflor 6', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Huevo con coliflor 6', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Huevo con coliflor 6', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Huevo con coliflor 6', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Pollo con brocoli 7', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Pollo con brocoli 7', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Pollo con brocoli 7', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Pollo con brocoli 7', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Ternera con zanahoria 8', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Ternera con zanahoria 8', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Ternera con zanahoria 8', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Ternera con zanahoria 8', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Pavo con coliflor 9', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Pavo con coliflor 9', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Pavo con coliflor 9', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Pavo con coliflor 9', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Salmon con brocoli 10', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Salmon con brocoli 10', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Salmon con brocoli 10', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Salmon con brocoli 10', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Merluza con zanahoria 11', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Merluza con zanahoria 11', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Merluza con zanahoria 11', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Merluza con zanahoria 11', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Bacalao con coliflor 12', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Bacalao con coliflor 12', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Bacalao con coliflor 12', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Bacalao con coliflor 12', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Atun con brocoli 13', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Atun con brocoli 13', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Atun con brocoli 13', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Atun con brocoli 13', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Tofu con zanahoria 14', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Tofu con zanahoria 14', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Tofu con zanahoria 14', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Tofu con zanahoria 14', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Huevo con coliflor 15', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Huevo con coliflor 15', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Huevo con coliflor 15', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Huevo con coliflor 15', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Pollo con brocoli 16', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Pollo con brocoli 16', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Pollo con brocoli 16', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Pollo con brocoli 16', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Ternera con zanahoria 17', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Ternera con zanahoria 17', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Ternera con zanahoria 17', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Ternera con zanahoria 17', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Pavo con coliflor 18', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Pavo con coliflor 18', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Pavo con coliflor 18', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Pavo con coliflor 18', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Salmon con brocoli 19', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Salmon con brocoli 19', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Salmon con brocoli 19', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Salmon con brocoli 19', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Cena Merluza con zanahoria 20', 1, 'Preparar los ingredientes priorizando una coccion ligera.'),
    ('Cena Merluza con zanahoria 20', 2, 'Cocinar la proteina a fuego medio hasta que quede hecha.'),
    ('Cena Merluza con zanahoria 20', 3, 'Anadir verduras y acompanamientos, ajustando textura y punto de coccion.'),
    ('Cena Merluza con zanahoria 20', 4, 'Servir caliente o templado en una racion equilibrada.'),
    ('Snack Queso fresco con almendras 1', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Queso fresco con almendras 1', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Queso fresco con almendras 1', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Queso fresco con almendras 1', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Yogur con nueces 2', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Yogur con nueces 2', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Yogur con nueces 2', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Yogur con nueces 2', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Atun con pepino 3', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Atun con pepino 3', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Atun con pepino 3', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Atun con pepino 3', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Huevo con tomate 4', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Huevo con tomate 4', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Huevo con tomate 4', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Huevo con tomate 4', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Pera con rucula 5', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Pera con rucula 5', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Pera con rucula 5', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Pera con rucula 5', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Bebida soja con semillas chia 6', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Bebida soja con semillas chia 6', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Bebida soja con semillas chia 6', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Bebida soja con semillas chia 6', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Garbanzos con almendras 7', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Garbanzos con almendras 7', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Garbanzos con almendras 7', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Garbanzos con almendras 7', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Tofu con nueces 8', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Tofu con nueces 8', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Tofu con nueces 8', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Tofu con nueces 8', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Pavo con pepino 9', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Pavo con pepino 9', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Pavo con pepino 9', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Pavo con pepino 9', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Manzana con tomate 10', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Manzana con tomate 10', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Manzana con tomate 10', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Manzana con tomate 10', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Queso fresco con rucula 11', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Queso fresco con rucula 11', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Queso fresco con rucula 11', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Queso fresco con rucula 11', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Yogur con semillas chia 12', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Yogur con semillas chia 12', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Yogur con semillas chia 12', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Yogur con semillas chia 12', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Atun con almendras 13', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Atun con almendras 13', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Atun con almendras 13', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Atun con almendras 13', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Huevo con nueces 14', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Huevo con nueces 14', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Huevo con nueces 14', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Huevo con nueces 14', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Pera con pepino 15', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Pera con pepino 15', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Pera con pepino 15', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Pera con pepino 15', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Bebida soja con tomate 16', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Bebida soja con tomate 16', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Bebida soja con tomate 16', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Bebida soja con tomate 16', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Garbanzos con rucula 17', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Garbanzos con rucula 17', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Garbanzos con rucula 17', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Garbanzos con rucula 17', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Tofu con semillas chia 18', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Tofu con semillas chia 18', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Tofu con semillas chia 18', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Tofu con semillas chia 18', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Pavo con almendras 19', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Pavo con almendras 19', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Pavo con almendras 19', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Pavo con almendras 19', 4, 'Servir como tentempie o conservar en frio si procede.'),
    ('Snack Manzana con nueces 20', 1, 'Preparar los ingredientes del snack y elegir una racion pequena.'),
    ('Snack Manzana con nueces 20', 2, 'Montar, mezclar o calentar brevemente segun corresponda.'),
    ('Snack Manzana con nueces 20', 3, 'Comprobar textura y anadir el acompanamiento indicado.'),
    ('Snack Manzana con nueces 20', 4, 'Servir como tentempie o conservar en frio si procede.')
)
INSERT INTO recipe_steps (recipe_id, step_number, description)
SELECT r.id, seed.step_number, seed.description FROM step_seed seed JOIN recipes r ON r.name = seed.recipe_name ORDER BY r.name, seed.step_number;

SELECT COUNT(*) AS recetas_seed_100 FROM recipes WHERE name IN (
    'Desayuno Avena con arandanos 1',
    'Desayuno Huevo con fresas 2',
    'Desayuno Pan integral con manzana 3',
    'Desayuno Bebida soja con pera 4',
    'Desayuno Quinoa con naranja 5',
    'Desayuno Avena con kiwi 6',
    'Desayuno Huevo con platano 7',
    'Desayuno Pan integral con arandanos 8',
    'Desayuno Bebida soja con fresas 9',
    'Desayuno Quinoa con manzana 10',
    'Desayuno Avena con pera 11',
    'Desayuno Huevo con naranja 12',
    'Desayuno Pan integral con kiwi 13',
    'Desayuno Bebida soja con platano 14',
    'Desayuno Quinoa con arandanos 15',
    'Desayuno Avena con fresas 16',
    'Desayuno Huevo con manzana 17',
    'Desayuno Pan integral con pera 18',
    'Desayuno Bebida soja con naranja 19',
    'Desayuno Quinoa con kiwi 20',
    'Comida Pollo con arroz 1',
    'Comida Ternera con pasta integral 2',
    'Comida Pavo con boniato 3',
    'Comida Salmon con garbanzos 4',
    'Comida Merluza con guisantes 5',
    'Comida Bacalao con quinoa 6',
    'Comida Atun con patata 7',
    'Comida Tofu con lentejas 8',
    'Comida Huevo con alubias 9',
    'Comida Pollo con arroz 10',
    'Comida Ternera con pasta integral 11',
    'Comida Pavo con boniato 12',
    'Comida Salmon con garbanzos 13',
    'Comida Merluza con guisantes 14',
    'Comida Bacalao con quinoa 15',
    'Comida Atun con patata 16',
    'Comida Tofu con lentejas 17',
    'Comida Huevo con alubias 18',
    'Comida Pollo con arroz 19',
    'Comida Ternera con pasta integral 20',
    'Comida Pavo con boniato 21',
    'Comida Salmon con garbanzos 22',
    'Comida Merluza con guisantes 23',
    'Comida Bacalao con quinoa 24',
    'Comida Atun con patata 25',
    'Comida Tofu con lentejas 26',
    'Comida Huevo con alubias 27',
    'Comida Pollo con arroz 28',
    'Comida Ternera con pasta integral 29',
    'Comida Pavo con boniato 30',
    'Comida Salmon con garbanzos 31',
    'Comida Merluza con guisantes 32',
    'Comida Bacalao con quinoa 33',
    'Comida Atun con patata 34',
    'Comida Tofu con lentejas 35',
    'Comida Huevo con alubias 36',
    'Comida Pollo con arroz 37',
    'Comida Ternera con pasta integral 38',
    'Comida Pavo con boniato 39',
    'Comida Salmon con garbanzos 40',
    'Cena Salmon con brocoli 1',
    'Cena Merluza con zanahoria 2',
    'Cena Bacalao con coliflor 3',
    'Cena Atun con brocoli 4',
    'Cena Tofu con zanahoria 5',
    'Cena Huevo con coliflor 6',
    'Cena Pollo con brocoli 7',
    'Cena Ternera con zanahoria 8',
    'Cena Pavo con coliflor 9',
    'Cena Salmon con brocoli 10',
    'Cena Merluza con zanahoria 11',
    'Cena Bacalao con coliflor 12',
    'Cena Atun con brocoli 13',
    'Cena Tofu con zanahoria 14',
    'Cena Huevo con coliflor 15',
    'Cena Pollo con brocoli 16',
    'Cena Ternera con zanahoria 17',
    'Cena Pavo con coliflor 18',
    'Cena Salmon con brocoli 19',
    'Cena Merluza con zanahoria 20',
    'Snack Queso fresco con almendras 1',
    'Snack Yogur con nueces 2',
    'Snack Atun con pepino 3',
    'Snack Huevo con tomate 4',
    'Snack Pera con rucula 5',
    'Snack Bebida soja con semillas chia 6',
    'Snack Garbanzos con almendras 7',
    'Snack Tofu con nueces 8',
    'Snack Pavo con pepino 9',
    'Snack Manzana con tomate 10',
    'Snack Queso fresco con rucula 11',
    'Snack Yogur con semillas chia 12',
    'Snack Atun con almendras 13',
    'Snack Huevo con nueces 14',
    'Snack Pera con pepino 15',
    'Snack Bebida soja con tomate 16',
    'Snack Garbanzos con rucula 17',
    'Snack Tofu con semillas chia 18',
    'Snack Pavo con almendras 19',
    'Snack Manzana con nueces 20'
);
